[tool.poetry]
name = "hugr-llvm"
version = "0.1.0"
description = ""
authors = ["Douglas Wilson"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
guppylang= "^0.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
