[package]
name = "qir-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
llvm-plugin = { version =  "0.6.0", features = ["llvm14-0"] }
inkwell = { version = "0.4.0", default-features = false, features = ["llvm14-0"] }
